### PR TITLE
#64 Updating fasta header parsing to support new NCBI fasta header.

### PR DESCRIPTION
**Pull request by andreasprlic**
This PR enables support for the new NCBI fasta format and addresses #64 .

### CODE REVIEW

**Comment by reece** [comment]
@andreasprlic: tests are failing. I suspect it's unrelated to your PR, but I want to investigate before merging. I'll need a few days at least. (I'm on vacation ATM.)

**Comment by andreasprlic** [comment]
yea, looks like some package dependency issue when run on Travis. I'll take a look at how to resolve.

**Comment by andreasprlic** [comment]
Updated the PR with a fix for the build dependencies for Travis. Also had to fix an unrelated unit test that for some reasons had a minor issue.

**Comment by reece** [comment]
Fabulous. Thanks @andreasprlic! Sorry for the delay.

**Pull request merged**
